### ISSUE TITLE
Should we remove unused blogs from planetsuse/feeds?

### ISSUE THREAD

**Issue by Ana06** [openSUSE/planet.opensuse.org#64]
1. There are many comment lines in this file, including complete feeds. But as this information is really easy to recreate (I guess everybody remember his name and IRC nickname :stuck_out_tongue_winking_eye: ) and do not see the point in keeping them. Taking into account that the file has more than 2000 lines, it would be nice to make it smaller. :wink: 

2. There are many entries which doesn't work. That is what I get when running the update script:
  ![image](https://user-images.githubusercontent.com/16052290/38086669-86b0f09c-3355-11e8-9c7f-ff599db55959.png)
  If they are broken, we can remove them as well. :wink:

**Comment by cboltz** [comment]
I'm happy to see you want to help with maintaining planet.o.o :-)

For the commented out lines - the file is big enough to always use the search function anyway, so they don't hurt ;-) but it also won't hurt to remove them. So - your choice ;-)

For the 404s, I already sent a list to the opensuse-project and opensuse-factory mailinglists some days ago, in the hope that people will speak up and tell us their updated feed location. Give them a few days for that, even if my hope that they'll really respond isn't too big. (Note that I checked my list multiple times over several weeks - deleting a blog just because it fails (only) today isn't a good idea IMHO.)

For all the 301 redirects, feel free to adjust the feed list. These are permanent redirects (most of them `http -> https`), so we can easily make them really;-)  permanent in the feed list.

**Comment by cboltz** [comment]
Stasiek did the cleanup while migrating to the planet-o-o repo
