### ISSUE TITLE
Suggestion to reduce the number of items to read

### ISSUE THREAD

**Issue by victorhck** [openSUSE/planet.opensuse.org#77]
Hello.
Time ago I canceled my subscription to planet.o.o due a annoying feature.
I have a suggestion (don't know if fits here): It's possible to publish only one article a day for the same blog?
Actually some blogs publish up to 6 articles a day (and not always related to openSUSE) and it's a bit "flood" in the planet.o.o timeline.
(The items I publish in my blog, syndicated in planet.o.o, are not always related to openSUSE, but at least don't publish more than 1 in a day)
Greetings

**Comment by cboltz** [comment]
I'm afraid such a limit isn't possible with the software we use - and besides that, it would have hit you because IIRC you published two articles the day after opening this issue ;-)

That said - we discussed this in the board, reviewed the "flooding" feed's content (which is not really openSUSE-related) and decided to remove it from planet.o.o.

Feel free to subscribe again ;-)

**Comment by victorhck** [comment]
Ok! Great!
Have a lot of fun!!
